/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Dk7bO3qKmNt
 */
import { Badge } from "@/components/ui/badge";

export function Matches() {
  return (
    <div className="bg-[#0d0d0d] text-white p-4 rounded-lg w-[400px]">
      <div className="text-xs font-bold uppercase text-[#ff3f3f] mb-2">
        Trendyol Süper Lig Sofascore Reytingi
      </div>
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <div className="h-12 flex flex-row items-center justify-center gap-x-[2px] bg-zinc-800">
            <div className="w-auto h-8 flex items-center justify-center bg-black">
              <div className="relative h-8 flex flex-row items-center pl-16 pr-4 justify-start overflow-hidden">
                <Image
                  alt="Team Logo"
                  className="absolute left-1.5 top-[50%] -translate-y-[50%] h-12 w-12 z-10"
                  height={48}
                  width={48}
                  src={`https://api.sofascore.app/api/v1/team/${form?.event?.homeTeam?.id}/image`}
                  style={{
                    aspectRatio: "1",
                    objectFit: "cover",
                  }}
                />
                <span className="text-zinc-100 font-extrabold relative">
                  {form?.event?.homeTeam?.nameCode}
                </span>
                <span
                  className="absolute w-full h-1 top-auto bottom-0 right-0 left-0"
                  style={{
                    background: form?.event?.homeTeam?.teamColors?.primary,
                  }}
                />
              </div>

              <div className="h-8 w-8 aspect-square font-bold text-lg flex items-center justify-center bg-white text-black ">
                {form?.event?.homeScore?.normaltime}
              </div>
            </div>
            <div className="w-auto h-8 flex flex-row-reverse items-center justify-center bg-black">
              <div className="relative h-8 flex items-center pr-16 pl-4 justify-end overflow-hidden">
                <Image
                  alt="Team Logo"
                  className="absolute right-1.5 top-[50%] -translate-y-[50%] h-12 w-12 z-10"
                  height={48}
                  width={48}
                  src={`https://api.sofascore.app/api/v1/team/${form?.event?.awayTeam?.id}/image`}
                  style={{
                    aspectRatio: "1",
                    objectFit: "cover",
                  }}
                />
                <span className="text-zinc-100 font-extrabold relative">
                  {form?.event?.awayTeam?.nameCode}
                </span>
                <span
                  className="absolute w-full h-1 top-auto bottom-0 right-0 left-0"
                  style={{
                    background: form?.event?.awayTeam?.teamColors?.primary,
                  }}
                />
              </div>

              <div className="h-8 w-8 aspect-square font-bold text-lg flex items-center justify-center bg-white text-black ">
                {form?.event?.awayScore?.normaltime}
              </div>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">21.01.21</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs">Trabzonspor</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
          </div>
          <div className="flex items-center space-x-1">
            <div className="text-xs">1</div>
            <div className="text-xs font-bold">5</div>
            <Badge variant="secondary">W</Badge>
          </div>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">25.01.21</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs">İstanbulspor</div>
          </div>
          <div className="flex items-center space-x-1">
            <div className="text-xs">3</div>
            <div className="text-xs font-bold">1</div>
            <Badge variant="secondary">W</Badge>
          </div>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">29.01.21</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs">Gaziantep</div>
          </div>
          <div className="flex items-center space-x-1">
            <div className="text-xs">2</div>
            <div className="text-xs font-bold">1</div>
            <Badge variant="secondary">W</Badge>
          </div>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">02.02.21</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs">Samsunspor</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
          </div>
          <div className="flex items-center space-x-1">
            <div className="text-xs">0</div>
            <div className="text-xs font-bold">2</div>
            <Badge variant="secondary">W</Badge>
          </div>
        </div>
        <div className="text-xs font-bold uppercase text-[#ff3f3f] mb-2">
          Türkiye Kupası
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">06.02.21</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs">Bandırmaspor</div>
          </div>
          <div className="flex items-center space-x-1">
            <div className="text-xs">4</div>
            <div className="text-xs font-bold">2</div>
            <Badge variant="secondary">W</Badge>
          </div>
        </div>
        <div className="text-xs font-bold uppercase text-[#ff3f3f] mb-2">
          Trendyol Süper Lig Sofascore Reytingi
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">10.02.21</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs">Başakşehir</div>
          </div>
          <div className="flex items-center space-x-1">
            <div className="text-xs">2</div>
            <div className="text-xs font-bold">0</div>
            <Badge variant="destructive">W</Badge>
          </div>
        </div>
        <div className="text-xs font-bold uppercase text-[#ff3f3f] mb-2">
          UEFA Europa League Sofascore Reytingi
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">15.02.21</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs">Sparta Praha</div>
          </div>
          <div className="flex items-center space-x-1">
            <div className="text-xs">3</div>
            <div className="text-xs font-bold">2</div>
            <Badge variant="secondary">W</Badge>
          </div>
        </div>
        <div className="text-xs font-bold uppercase text-[#ff3f3f] mb-2">
          Trendyol Süper Lig Sofascore Reytingi
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="text-[#8a8a8a] text-xs">18.02.21</div>
            <ClockIcon className="h-4 w-4" />
            <div className="text-xs">19:00</div>
            <FlagIcon className="h-4 w-4" />
            <div className="text-xs">Ankaragücü</div>
            <XIcon className="h-4 w-4" />
            <div className="text-xs font-bold">Galatasaray</div>
          </div>
          <MoreHorizontalIcon className="h-4 w-4" />
        </div>
      </div>
    </div>
  );
}

function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}

function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  );
}

function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  );
}
